# Generated by Django 3.2.3 on 2024-12-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
    ]
