# Generated by Django 3.2.3 on 2024-12-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_is_in_stock'),
        ('orders', '0003_remove_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.robot'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.BooleanField(default=False),
        ),
    ]
